"""What changes when CODE_GENDER is taken out of the model, and what still stands in for it.

Trains the model twice on the same split, once with CODE_GENDER as an input and once
without (the default in src/model.py), and compares the decisions for women and men at
each model's own 20% decline threshold. Then it checks how much gender information the
remaining inputs still carry:
  1. Gender predictability: a logistic regression that predicts gender from the model's
     inputs. ROC-AUC 0.5 would mean no gender signal left; 1.0 would mean full.
  2. Proxies: correlation of each input with gender, next to that input's SHAP
     importance in the model without gender. An input that is both important and
     correlated with gender can carry gender into the decision.

Run:  python -m src.gender_check     (trains two models, about 6 minutes)
Writes reports/gender_check.md and reports/gender_check.json.
"""
from __future__ import annotations
import json

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

from . import explain
from . import model as M
from .config import RANDOM_STATE

GROUP_COLS = ["approval_rate", "tpr", "fpr", "observed_rate", "mean_pd"]


def gender_rows(m):
    rows = {r["group"]: r for r in m["fairness"]["gender"]}
    return rows["F"], rows["M"]


def proxy_table(art, top_shap=20, min_corr=0.10):
    names = [n.split("__", 1)[-1] for n in art["pre"].get_feature_names_out()]
    known = art["X_tr"]["CODE_GENDER"].isin(["F", "M"]).to_numpy()
    is_male = (art["X_tr"]["CODE_GENDER"] == "M").to_numpy()[known].astype(float)
    X = art["Xtr"][known]
    Xc = X - X.mean(axis=0)
    yc = is_male - is_male.mean()
    denom = np.sqrt((Xc ** 2).sum(axis=0) * (yc ** 2).sum())
    corr = np.divide(Xc.T @ yc, denom, out=np.zeros(X.shape[1]), where=denom > 0)

    _, sv, _ = explain.shap_values_for(art["lgbm"], art["Xte"], sample=2000, seed=RANDOM_STATE)
    imp = np.abs(sv).mean(axis=0)
    rank = np.empty_like(imp, dtype=int)
    rank[np.argsort(-imp)] = np.arange(1, len(imp) + 1)
    df = pd.DataFrame({"feature": names, "corr_with_male": corr, "mean_abs_shap": imp,
                       "shap_rank": rank})
    proxies = df[(df.shap_rank <= top_shap) & (df.corr_with_male.abs() >= min_corr)]
    most_corr = df.reindex(df.corr_with_male.abs().sort_values(ascending=False).index).head(10)
    return proxies.sort_values("shap_rank"), most_corr


def gender_predictability(art):
    tr = art["X_tr"]["CODE_GENDER"].isin(["F", "M"]).to_numpy()
    te = art["X_te"]["CODE_GENDER"].isin(["F", "M"]).to_numpy()
    y_tr = (art["X_tr"]["CODE_GENDER"] == "M").to_numpy()[tr]
    y_te = (art["X_te"]["CODE_GENDER"] == "M").to_numpy()[te]
    clf = LogisticRegression(max_iter=2000).fit(art["Xtr"][tr], y_tr)
    return float(roc_auc_score(y_te, clf.predict_proba(art["Xte"][te])[:, 1]))


def main():
    df = M.load_frame()
    kw = dict(n_boot=200, figures=False, save=False)
    with_g = M.run(df, exclude=(), **kw)
    art = {}
    without_g = M.run(df, artifacts=art, **kw)
    proxies, most_corr = proxy_table(art)
    auc_gender = gender_predictability(art)

    out = {"with_gender": {"roc_auc": with_g["models"]["lightgbm"]["roc_auc"],
                           "threshold": with_g["operating_point"]["threshold"],
                           "gender": with_g["fairness"]["gender"],
                           "age_band": with_g["fairness"]["age_band"]},
           "without_gender": {"roc_auc": without_g["models"]["lightgbm"]["roc_auc"],
                              "threshold": without_g["operating_point"]["threshold"],
                              "gender": without_g["fairness"]["gender"],
                              "age_band": without_g["fairness"]["age_band"]},
           "gender_predictability_auc": auc_gender,
           "proxies": proxies.to_dict(orient="records"),
           "most_gender_correlated": most_corr.to_dict(orient="records")}
    (M.REPORTS_DIR / "gender_check.json").write_text(json.dumps(out, indent=1), encoding="utf-8")

    L = ["# Taking CODE_GENDER out of the model", "",
         "Generated by `python -m src.gender_check`. Same 60/20/20 split as `python -m src.model`. "
         "Each model is judged at its own threshold for declining the riskiest 20% "
         "(set on the calibration split). All numbers are on the test split.", "",
         "## Decisions for women and men", "",
         "| Model | ROC-AUC | Group | Approval rate | TPR | FPR | Observed default rate | Mean calibrated PD |",
         "|---|---|---|---|---|---|---|---|"]
    for label, m in [("With gender", with_g), ("Without gender", without_g)]:
        for r in gender_rows(m):
            L.append(f"| {label} | {m['models']['lightgbm']['roc_auc']:.3f} | {r['group']} | "
                     f"{r['approval_rate']:.3f} | {r['tpr']:.3f} | {r['fpr']:.3f} | "
                     f"{r['observed_rate']:.3f} | {r['mean_pd']:.3f} |")
    L += ["", "Gap (men minus women):", "",
          "| Model | Approval rate | TPR | FPR |", "|---|---|---|---|"]
    for label, m in [("With gender", with_g), ("Without gender", without_g)]:
        f, mm = gender_rows(m)
        L.append(f"| {label} | {mm['approval_rate'] - f['approval_rate']:+.3f} | "
                 f"{mm['tpr'] - f['tpr']:+.3f} | {mm['fpr'] - f['fpr']:+.3f} |")
    L += ["", "TPR: share of applicants who had payment difficulties that the model declines. "
          "FPR: share of applicants who had none that the model declines.", "",
          "## How much gender the remaining inputs still carry", "",
          f"A logistic regression that predicts gender from the model's inputs (without "
          f"CODE_GENDER) reaches ROC-AUC {auc_gender:.3f} on the test split.", "",
          "Inputs in the top 20 by SHAP importance (model without gender) whose correlation "
          "with being male is at least 0.10 in size:", "",
          "| Feature | SHAP rank | Mean abs SHAP | Correlation with male |", "|---|---|---|---|"]
    for r in proxies.itertuples():
        L.append(f"| `{r.feature}` | {r.shap_rank} | {r.mean_abs_shap:.3f} | {r.corr_with_male:+.3f} |")
    L += ["", "The 10 inputs most correlated with gender, whatever their importance:", "",
          "| Feature | Correlation with male | SHAP rank |", "|---|---|---|"]
    for r in most_corr.itertuples():
        L.append(f"| `{r.feature}` | {r.corr_with_male:+.3f} | {r.shap_rank} |")
    (M.REPORTS_DIR / "gender_check.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
