"""Before/after check for the logistic regression convergence fix.

Trains three setups on the same train split and scores them on the same test split:
  1. the old setup exactly: scale without centring, saga, max_iter=1000, float64
  2. the old setup with the matrix cast to float32 (isolates the effect of precision)
  3. the new setup: centred features, lbfgs, max_iter=2000, float32 (as src/model.py)
The old ColumnTransformer returns a dense matrix here: the one-hot columns are sparse,
but the 100+ numeric columns push the overall density above its 0.3 cut-off.

Run:  python -m src.logreg_check     (a few minutes: saga is slow on 184k rows)
Writes reports/logreg_convergence.md.
"""
from __future__ import annotations
import time
import warnings

from sklearn.compose import ColumnTransformer
from sklearn.exceptions import ConvergenceWarning
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, average_precision_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

from . import features as F
from . import model as M


def old_preprocessor(X):
    numeric, categorical = F.split_columns(X)
    return ColumnTransformer([
        ("num", Pipeline([("impute", SimpleImputer(strategy="median")),
                          ("scale", StandardScaler(with_mean=False))]), numeric),
        ("cat", Pipeline([("impute", SimpleImputer(strategy="most_frequent")),
                          ("onehot", OneHotEncoder(handle_unknown="ignore"))]), categorical),
    ])


def fit_and_score(pre, clf, X_tr, y_tr, X_te, y_te, dtype="float64"):
    t0 = time.time()
    Xtr = pre.fit_transform(X_tr).astype(dtype)
    with warnings.catch_warnings(record=True) as w:
        warnings.simplefilter("always", ConvergenceWarning)
        clf.fit(Xtr, y_tr)
    p = clf.predict_proba(pre.transform(X_te).astype(dtype))[:, 1]
    return {"matrix": ("sparse " if hasattr(Xtr, "toarray") else "dense ") + dtype,
            "n_iter": int(clf.n_iter_[0]), "max_iter": clf.max_iter,
            "convergence_warning": any(issubclass(x.category, ConvergenceWarning) for x in w),
            "roc_auc": roc_auc_score(y_te, p), "pr_auc": average_precision_score(y_te, p),
            "seconds": round(time.time() - t0, 1)}


def main():
    (X_tr, y_tr), _, (X_te, y_te) = M.split(M.load_frame())
    saga = lambda: LogisticRegression(solver="saga", max_iter=1000, class_weight="balanced")  # noqa: E731
    old = fit_and_score(old_preprocessor(X_tr), saga(), X_tr, y_tr, X_te, y_te, "float64")
    old32 = fit_and_score(old_preprocessor(X_tr), saga(), X_tr, y_tr, X_te, y_te, "float32")
    new = fit_and_score(F.build_preprocessor(X_tr),
                        LogisticRegression(max_iter=2000, class_weight="balanced"),
                        X_tr, y_tr, X_te, y_te, "float32")
    lines = ["# Logistic regression: convergence before and after", "",
             "Generated by `python -m src.logreg_check`. Same 60% train split and 20% test "
             "split as `python -m src.model`.", "",
             "| Setup | Matrix | Iterations used | Convergence warning | ROC-AUC | PR-AUC | Seconds |",
             "|---|---|---|---|---|---|---|"]
    for name, r in [("Old: no centring, saga, max_iter=1000", old),
                    ("Old, matrix cast to float32", old32),
                    ("New: centred, lbfgs, max_iter=2000", new)]:
        lines.append(f"| {name} | {r['matrix']} | {r['n_iter']} of {r['max_iter']} | "
                     f"{r['convergence_warning']} | "
                     f"{r['roc_auc']:.4f} | {r['pr_auc']:.4f} | {r['seconds']} |")
    diff = new["roc_auc"] - old["roc_auc"]
    lines += ["", f"ROC-AUC change (new minus old): {diff:+.4f}."]
    out = M.REPORTS_DIR / "logreg_convergence.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
